#!/usr/bin/env bash

TEST_DIR=`pwd`/`dirname $0`
OUT_DIR=$TEST_DIR/../out
BUILD_DIR=$OUT_DIR/build
CACHE_DIR=$OUT_DIR/cache
ENV_DIR=$OUT_DIR/env


$TEST_DIR/../bin/compile $BUILD_DIR $CACHE_DIR $ENV_DIR
